create sequence hibernate_sequence start 122 increment 1;

create table orders (
    id int8 generated by default as identity,
    address varchar(255),
    city varchar(255),
    date date,
    email varchar(255),
    first_name varchar(255),
    last_name varchar(255),
    phone_number varchar(255),
    post_index int4 not null check (post_index >= 5),
    total_price float8,
    user_id int8,
    primary key (id)
);

create table orders_product_list (
    order_id int8 not null,
    product_list_id int8 not null,
    product_list_order int4 not null,
    primary key (order_id, product_list_order)
);

create table product (
    id int8 not null,
    product_title varchar(255) not null,
    manufacturer varchar(255) not null,
    year int4 not null,
    product_category varchar(255) not null,
    description varchar(255),
    filename varchar(255),
    price int4 not null,
    primary key (id)
);

create table review (
    id int8 not null,
    date date,
    message varchar(255),
    primary key (id)
);

ALTER TABLE review ADD COLUMN author VARCHAR(255) NOT NULL;

create table product_reviews (
    product_id int8 not null,
    reviews_id int8 not null
);

create table user_role (
    user_id int8 not null,
    roles varchar(255)
);

create table usr (
    id int8 not null,
    password_reset_code varchar(255),
    email varchar(255) not null,
    password varchar(255) not null,
    username varchar(255) not null,
    primary key (id)
);

create table usr_product_list (
    user_id int8 not null,
    product_list_id int8 not null
);

alter table if exists product_reviews
    add constraint UK_product_reviews_reviews_id unique (reviews_id);

alter table if exists orders
    add constraint FK_orders_user
    foreign key (user_id) references usr;

alter table if exists orders_product_list
    add constraint FK_orders_product_list_product
    foreign key (product_list_id) references product;

alter table if exists orders_product_list
    add constraint FK_orders_product_list_order
    foreign key (order_id) references orders;

alter table if exists product_reviews
    add constraint FK_product_reviews_review
    foreign key (reviews_id) references review;

alter table if exists product_reviews
    add constraint FK_product_reviews_product
    foreign key (product_id) references product;

alter table if exists user_role
    add constraint FK_user_role_user
    foreign key (user_id) references usr;

alter table if exists usr_product_list
    add constraint FK_usr_product_list_product
    foreign key (product_list_id) references product;

alter table if exists usr_product_list
    add constraint FK_usr_product_list_user
    foreign key (user_id) references usr;
