INSERT INTO product (id, product_title, manufacturer, product_category, price, description, filename, year) VALUES
(1, 'Apple', 'FreshFarms', 'food', 2, 'Fresh red apples', 'apple.jpg', 2023),
(2, 'Dining Table', 'WoodWorks', 'furniture', 150, 'Solid oak dining table', 'dining_table.jpg', 2022),
(3, 'Banana', 'TropiCo', 'food', 1, 'Organic bananas', 'banana.jpg', 2023),
(4, 'Sofa', 'ComfortHome', 'furniture', 400, 'Leather sofa', 'sofa.jpg', 2021),
(5, 'Bread', 'BakeHouse', 'food', 3, 'Whole wheat bread', 'bread.jpg', 2023),
(6, 'Chair', 'SeatingPro', 'furniture', 45, 'Ergonomic office chair', 'chair.jpg', 2022),
(7, 'Milk', 'DairyPure', 'food', 2, 'Fresh cow milk', 'milk.jpg', 2023),
(8, 'Bookshelf', 'FurniStore', 'furniture', 80, 'Wooden bookshelf', 'bookshelf.jpg', 2022),
(9, 'Orange', 'CitrusWorld', 'food', 3, 'Juicy oranges', 'orange.jpg', 2023),
(10, 'Bed', 'SleepWell', 'furniture', 350, 'Queen size bed', 'bed.jpg', 2021),
(11, 'Eggs', 'FarmFresh', 'food', 4, 'Organic eggs', 'eggs.jpg', 2023),
(12, 'Wardrobe', 'ClosetPro', 'furniture', 200, 'Spacious wardrobe', 'wardrobe.jpg', 2022),
(13, 'Tomato', 'VeggieMart', 'food', 2, 'Fresh tomatoes', 'tomato.jpg', 2023),
(14, 'Coffee Table', 'UrbanFurnish', 'furniture', 60, 'Modern coffee table', 'coffee_table.jpg', 2022),
(15, 'Rice', 'GrainHouse', 'food', 5, 'Basmati rice', 'rice.jpg', 2023),
(16, 'TV Stand', 'HomeDeco', 'furniture', 90, 'TV stand with shelves', 'tv_stand.jpg', 2022),
(17, 'Chicken', 'MeatMaster', 'food', 8, 'Fresh chicken meat', 'chicken.jpg', 2023),
(18, 'Desk', 'OfficePro', 'furniture', 120, 'Office desk', 'desk.jpg', 2022),
(19, 'Cheese', 'DairyLand', 'food', 6, 'Cheddar cheese', 'cheese.jpg', 2023),
(20, 'Recliner', 'RelaxHome', 'furniture', 250, 'Comfortable recliner', 'recliner.jpg', 2021),
(21, 'Pear', 'FreshFarms', 'food', 3, 'Juicy green pears', 'pear.jpg', 2023),
(22, 'Nightstand', 'WoodWorks', 'furniture', 55, 'Modern nightstand', 'nightstand.jpg', 2022),
(23, 'Pineapple', 'TropiCo', 'food', 4, 'Sweet pineapple', 'pineapple.jpg', 2023),
(24, 'Armchair', 'ComfortHome', 'furniture', 120, 'Soft armchair', 'armchair.jpg', 2021),
(25, 'Croissant', 'BakeHouse', 'food', 2, 'Buttery croissant', 'croissant.jpg', 2023),
(26, 'Stool', 'SeatingPro', 'furniture', 25, 'Bar stool', 'stool.jpg', 2022),
(27, 'Yogurt', 'DairyPure', 'food', 3, 'Greek yogurt', 'yogurt.jpg', 2023),
(28, 'Shoe Rack', 'FurniStore', 'furniture', 40, 'Compact shoe rack', 'shoe_rack.jpg', 2022),
(29, 'Lemon', 'CitrusWorld', 'food', 2, 'Fresh lemons', 'lemon.jpg', 2023),
(30, 'Mattress', 'SleepWell', 'furniture', 180, 'Memory foam mattress', 'mattress.jpg', 2021),
(31, 'Butter', 'FarmFresh', 'food', 5, 'Creamy butter', 'butter.jpg', 2023),
(32, 'Dresser', 'ClosetPro', 'furniture', 130, '6-drawer dresser', 'dresser.jpg', 2022),
(33, 'Cucumber', 'VeggieMart', 'food', 2, 'Crisp cucumbers', 'cucumber.jpg', 2023),
(34, 'Side Table', 'UrbanFurnish', 'furniture', 35, 'Round side table', 'side_table.jpg', 2022),
(35, 'Oats', 'GrainHouse', 'food', 4, 'Rolled oats', 'oats.jpg', 2023),
(36, 'Bookshelf', 'HomeDeco', 'furniture', 70, 'Tall bookshelf', 'bookshelf2.jpg', 2022),
(37, 'Beef', 'MeatMaster', 'food', 12, 'Grass-fed beef', 'beef.jpg', 2023),
(38, 'Filing Cabinet', 'OfficePro', 'furniture', 85, 'Metal filing cabinet', 'filing_cabinet.jpg', 2022),
(39, 'Milk Cheese', 'DairyLand', 'food', 7, 'Goat milk cheese', 'milk_cheese.jpg', 2023),
(40, 'Loveseat', 'RelaxHome', 'furniture', 220, '2-seater loveseat', 'loveseat.jpg', 2021);
